# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50, unique=True)),
                ('groupdesc', models.CharField(max_length=100)),
                ('actionstart', models.CharField(blank=True, max_length=200, null=True)),
                ('actionstop', models.CharField(blank=True, max_length=200, null=True)),
                ('actionrestart', models.CharField(blank=True, max_length=200, null=True)),
                ('actiondeploy', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50)),
                ('hostip', models.CharField(max_length=50, unique=True)),
                ('actionstart', models.CharField(blank=True, max_length=200, null=True)),
                ('actionstop', models.CharField(blank=True, max_length=200, null=True)),
                ('actionrestart', models.CharField(blank=True, max_length=200, null=True)),
                ('actiondeploy', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Groups')),
            ],
        ),
    ]
