# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20160603_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='optimes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
