# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_hosts_optimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='actiontype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
